### ISSUE TITLE
ModuleNotFoundError: No module named 'vocoder'

### ISSUE THREAD

**Issue by dto** [yangdongchao/Text-to-sound-Synthesis#4]
(specvqgan) dto@thexder:/apdcephfs/share_1316500/donchaoyang/code3/Text-to-sound-Synthesis/Codebook$ python3 evaluation/generate_samples.py 
Traceback (most recent call last):
  File "evaluation/generate_samples.py", line 17, in <module>
    from train import instantiate_from_config
  File "/apdcephfs/share_1316500/donchaoyang/code3/Text-to-sound-Synthesis/Codebook/./train.py", line 30, in <module>
    from vocoder.modules import Generator
ModuleNotFoundError: No module named 'vocoder'

**Comment by a43992899** [comment]
The code base seems to be a mess.... I am also experiencing this issue...
